### ISSUE TITLE
Downloading translations failed - debug logging?

### ISSUE THREAD

**Issue by mendhak** [crowdin/android-studio-plugin#1]
Hi I'm currently trying to use this plugin in IntelliJ IDEA.  I've created the `crowdin.properties` with project-key and project-identifier in it.  When I try to download the translations I get "Downloading translations failed".  I tried tailing the `idea.log` but there are no entries that appear in there at all.  

Possible to add some debug logging or instructions to troubleshoot?

**Comment by Andrulko** [comment]
Hi @mendhak, reviewing possible reasons why translations aren't synced. Thanks for your suggestion with debugging, this point will be reviewed as well

**Comment by ihor-popyk** [comment]
Hi @mendhak ,
fixed this bug in new version 0.5.4. Just update it.
Thanks for report!

**Comment by mendhak** [comment]
Hello @ihor-popyk @Andrulko - thanks, it worked, v0.5.4  thanks for your quick response.  I'll close now.
