### ISSUE TITLE
Error downloading translations

### ISSUE THREAD

**Issue by michaelWuensch** [crowdin/android-studio-plugin#10]
Hi, 
yesterday it worked fine. But today when I try to download translations I always get just this error:
"Downloading transactions failed"

This error is not very helpful, I have no idea what goes wrong or how I can find out what the error is.
Any help? Thanks!

**Comment by michaelWuensch** [comment]
Okay, I found the solution.
The problem was I switched the branch and therfore it did not work anymore.
Using disable-branches=true fixed it.

Still, I think the error message could be improved.

**Comment by andrii-bodnar** [comment]
Fixed in 1.0.0 version
