### ISSUE TITLE
Write Unit test for the `CrowdinProjectCacheProvider::getInstance` method

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/android-studio-plugin#100]
Currently, this method is not covered by Unit tests.

- [Actual coverage](https://app.codecov.io/gh/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/client/CrowdinProjectCacheProvider.java)
- [CrowdinProjectCacheProviderTest.java](https://github.com/crowdin/android-studio-plugin/blob/master/src/test/java/com/crowdin/client/CrowdinProjectCacheProviderTest.java)
- [CrowdinProjectCacheProvider.java](https://github.com/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/client/CrowdinProjectCacheProvider.java)

**Comment by iremugurlu** [comment]
Hey, I'm interested. Can you assign this one to me?

**Comment by andrii-bodnar** [comment]
Hi @iremugurlu, do you have any updates on this?

**Comment by iremugurlu** [comment]
Hi @andrii-bodnar, sorry I didn't have much time to look at it. It has been a busy week. Feel free to assign someone else.
