### ISSUE TITLE
Unable to make plugin work with project sharing iOS and Android sources

### ISSUE THREAD

**Issue by NeverwinterMoon** [crowdin/android-studio-plugin#109]
```
project-id=<CORRECT-ID>
api-token=<CORRECT-TOKEN>
disable-branches=true
preserve-hierarchy=true
files.source=common/src/main/res/values/strings.xml
files.translation=common/src/main/res/values-%two_letters_code%/%original_file_name%
debug=true
```

<img width="530" alt="image" src="https://github.com/crowdin/android-studio-plugin/assets/1917308/2cc27a6c-8180-4ae3-ac8a-87553c69d87c">

I have managed to run upload sources successfully.

On trying to download translations:

The translations for the following sources will be ommited: - /strings.xml The translations with unfound sources: - /hi/Localizable.strings - /pl/Localizable.strings - /en/Localizable.strings - /lt/Localizable.strings - /uk/Localizable.strings - /pt-BR/Localizable.strings - /zh-CN/Localizable.strings - /th/Localizable.strings - /fi/Localizable.strings - /ja/Localizable.strings - /it/Localizable.strings - /lv/Localizable.strings - /et/Localizable.strings - /en-GB/Localizable.strings - /ka/Localizable.strings - /sl/Localizable.strings - /sv-SE/Localizable.strings - /fr/Localizable.strings - /hr/Localizable.strings - /de/Localizable.strings - /es-ES/Localizable.strings - /ru/Localizable.strings - /ro/Localizable.strings

It tries to handle iOS translations for some reason. I don't mind the warning, but it actually does not download the Android ones.

I am managing the Android project only and don't care about the iOS transactions for now.

**Comment by NeverwinterMoon** [comment]
OK, I think the problem is with nesting. I managed to make it work if I upload the structure as /common/src/main/res/values/values.xml. But I don't want that actually, I prefer the flat structure I had before. This structure works:

<img width="625" alt="image" src="https://github.com/crowdin/android-studio-plugin/assets/1917308/d3f81532-c1ad-4d6a-8c97-3a7cd930a607">

The flat one does not.

**Comment by jbushmaster007** [comment]
content/apps/maintaining-github-apps/activating-optional-features-for-github-apps.md

**Comment by andrii-bodnar** [comment]
The `preserve-hierarchy=false` is supposed to provide a "flat" file structure in the Crowdin project. 

But you still need to specify the `translation` pattern in your configuration file and make sure that this pattern is set as a "_resulting file after translation export_" for your source file in Crowdin (the Crowdin Android Studio plugin will set this pattern automatically during the sources upload).

Please refer to [this documentation](https://crowdin.github.io/crowdin-cli/faq#downloaded-translations-dont-match-the-current-project-configuration) (this is CLI documentation, but the issue described is the same).
