### ISSUE TITLE
Update icons 🎨

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/android-studio-plugin#110]
Crowdin has recently [updated its logo](https://crowdin.com/blog/2023/07/31/what-is-new-at-crowdin-july-2023#updated-crowdin-logo-unveiled).

We need to update all the logo icons with the same size and image extension.

**Sources:**

- https://github.com/crowdin/android-studio-plugin/tree/master/src/main/resources/META-INF
- https://github.com/crowdin/android-studio-plugin/tree/master/src/main/resources/icons

[**Media Kit**](https://support.crowdin.com/using-logo/) 🎨

**Comment by indra057** [comment]
i think i need to update the logo of .svg file in META-in
also in resources/icons/ all the three icon.svg , icon 80x80.svg ,icon dark.svg ...do i need to update the icons of anywhere else.??can u plzz assign me this issue.. !
