### ISSUE TITLE
Version 1.6.2 breaks auto-completion

### ISSUE THREAD

**Issue by M66B** [crowdin/android-studio-plugin#115]
**Describe the bug**
Version 1.6.2 breaks auto-completion!

**To Reproduce**
1. Update to version 1.6.2
2. Restart Android Studio

**Environment:**
1. Android Studio Giraffe | 2022.3.1 Patch 2
2. Ubuntu

**Expected behavior**
Auto-completion keeps working, obviously.

**Screenshots**

**Additional context**

Run the plugin in Debug mode and provide an extended log.
To enable Debug mode add `debug=true` to the *crowdin.properties* file.

```
Error from server:  , Message: Unrecognized field "excludeCodeBlocks" (class com.crowdin.client.sourcefiles.model.OtherFileImportOptions), not marked as ignorable (2 known properties: "contentSegmentation", "customSegmentation"]) at [Source: (String)"{"contentSegmentation":true,"customSegmentation":false,"excludeCodeBlocks":false,"excludedFrontMatterElements":[]}"; line: 1, column: 81] (through reference chain: com.crowdin.client.sourcefiles.model.FileInfoResponseList["data"]->java.util.ArrayList[1]->com.crowdin.client.sourcefiles.model.FileResponseObject["data"]->com.crowdin.client.sourcefiles.model.File["importOptions"]->com.crowdin.client.sourcefiles.model.OtherFileImportOptions["excludeCodeBlocks"])>
```

**Comment by M66B** [comment]
In fact, downloading translation doesn't work for me anymore, also not when downgrading to version 1.6.1.
Is there something changed to the server API that the plugin doesn't understand anymore?

**Comment by DimaYashchyshyn** [comment]
Hello @M66B 
The list of changes can be found in the [changelog](https://github.com/crowdin/android-studio-plugin/blob/master/CHANGELOG.md), you may refer to it. 

As far as I'm aware, there haven't been any recent changes to the server API that would affect the plugin. However, to better assist you, could you please provide the name of the project where this issue is occurring?

**Comment by M66B** [comment]
@DimaYashchyshyn https://github.com/M66B/FairEmail

**Comment by andrii-bodnar** [comment]
Requires updating the Crowdin Java client to the latest version

https://github.com/crowdin/android-studio-plugin/blob/master/build.gradle#L24
https://github.com/crowdin/crowdin-api-client-java/releases/tag/1.12.0

**Comment by M66B** [comment]
@andrii-bodnar Shouldn't the Crowdin Android Studio plugin take care of this?

**Comment by andrii-bodnar** [comment]
@M66B this error comes from the API client due to the response serialization issue. We need to update this dependency in the Crowdin Android Studio plugin.

**Comment by M66B** [comment]
Why should an app compile this? This is an Android Studio / plugin problem.

**Comment by M66B** [comment]
When will the Android Studio Crowdin plugin be updated? As it is, it is completely unusable, and it is only causing problems for other things, like auto-completion. IMHO, this is a rather critical issue.

**Comment by andrii-bodnar** [comment]
@M66B please try the [1.6.3](https://github.com/crowdin/android-studio-plugin/releases/tag/1.6.3) version.

**Comment by M66B** [comment]
@andrii-bodnar I don't use the Crowdin Android Studio plugin anymore.
