### ISSUE TITLE
Crowdin Pluggin android studio Download section empty

### ISSUE THREAD

**Issue by iZakirSheikh** [crowdin/android-studio-plugin#140]
**Describe the bug**
I can clearly see the files in upload section and progress section. but there are no- files in Download section.

**Environment:**
1. Android Studio Ladybug
2. OS version Windows 11

**Comment by andrii-bodnar** [comment]
Hi @iZakirSheikh, please provide your `crowdin.yml` configuration file and an example of the structure of localization files in the project.

**Comment by iZakirSheikh** [comment]
Hello @andrii-bodnar, I have partially resolved the issue by first manually downloading the empty translation files from Crowdin as a zip file and then moving them to my app folder. After this, the download section began to function normally. Below is my Crowdin .yml file; please note that I provide the API Key and project ID in the plugin settings 

preserve_hierarchy: true
files:
  - source: "**/values/strings.xml"
    translation: "/values-%android_code%/%original_file_name%" #CORRECT
    update_strings: true
    cleanup_mode: true
    import_eq_suggestions: true
    auto_approve_imported: true
    translate_hidden: true
    # This will be converted to 'app/src/main/res/values-%two_letter_code%/%original_file_name%' export pattern for each file

**Comment by andrii-bodnar** [comment]
@iZakirSheikh yes, actually it's expected behavior because plugin relies on local translation files while rendering the file tree in the Downloads tab.

**Comment by iZakirSheikh** [comment]
> @iZakirSheikh yes, actually it's expected behavior because plugin relies on local translation files while rendering the file tree in the Downloads tab.

Thank you for the clarification. However, it would have been helpful if this was explicitly mentioned, perhaps in the GitHub README of the plugin—it could have saved a lot of time.

Additionally, I noticed that downloading translations takes longer than expected, even though the files are only a few kilobytes in size. Ideally, this process should happen on the fly for better efficiency.

Lastly, I’d suggest making the plugin's buttons more intuitive. For example, placing the "Download Sources" button right next to "Download Translation" can be confusing, as users may not always want to update sources from Crowdin.

Thanks!

**Comment by andrii-bodnar** [comment]
@iZakirSheikh thanks for your suggestions!
