### ISSUE TITLE
Configure auto upload

### ISSUE THREAD

**Issue by jonathan-mediamonks** [crowdin/android-studio-plugin#2]
Hi, we are trying out the new Crowdin plugin. As it's really easy to setup it would be great if the auto-upload could be turned off some way. It's for example not convenient to upload the strings.xml every time a developer switches branches.

**Comment by ihor-popyk** [comment]
Hi @jonathan-mediamonks . Thank you for your advice on improving our plugin. I'll add this option with the next update of the plugin.

**Comment by AllanWang** [comment]
Something needs to be done about the way it is downloaded as well. If you switch to a new branch and don't upload, downloads will all fail as there's nothing to pull  in

**Comment by Andrulko** [comment]
Hi @AllanWang, thanks for another improvement idea for the plugin! The main problem here I guess is that branches are not fully supported yet, so the issue occurs unfortunately

**Comment by AllanWang** [comment]
I had quite a few conflicts with the plugin, but I'm happy to see that this along with the cli are open sourced. For the branch issue, is this something you plan on fixing on the back end? 

At least in the case of hiding duplicates, can the plugin verify that setting and automatically push and pull?

There are a few other blips I've encountered that I will post as separate issues

**Comment by Andrulko** [comment]
@AllanWang There are some technical obstacles, but it should be possible to implement normal workflow with branches, lookign into that.

The plugin doesn't control settings in Crowdin, it just push and pulls. If duplicates are hidden and auto-translated in the project, you will always get the same download results via web interface / CLI / plugin. Files are generated by Crowdin, plugin just imports them to Android Studio.

**Comment by AllanWang** [comment]
I'm not referring to modifying settings, but moreso accessing. For instance, if you are able to pull the user settings and see that they choose to ignore duplicates, there is no danger in pushing strings, and downloading them. In the case of translations per duplicate, doing so may be useless as no translations will be merged.

**Comment by andrii-bodnar** [comment]
`auto-upload` option
