### ISSUE TITLE
Support multiple modules

### ISSUE THREAD

**Issue by AllanWang** [crowdin/android-studio-plugin#3]
The plugin was build with the expectancy of only one module per project. If a project has multiple submodules, each with their own string data, downloading the strings will aggregate it all to one of the submodules.

Example:

If you have 

`a/src/main/java/res/values/strings_a.xml`

and

`b/src/main/java/res/values/strings_b.xml`

downloading them may put them both under `b/src/main/java/res/values/`

Easiest way to fix this is to store the absolute path as you send it (or at the very least, search through the subdirectory to locate the named file to figure out where it is). The latter may not support multiple modules with the same file name (`strings.xml`), but it's a start.

**Comment by diego-depop** [comment]
Any update on this?

**Comment by andrii-bodnar** [comment]
@AllanWang @diego-depop hi,

in the [1.1.0](https://github.com/crowdin/android-studio-plugin/releases/tag/1.1.0) version we have added a possibility to [configure](https://github.com/crowdin/android-studio-plugin#source-files-and-translations) custom source and translation files patterns. 

Could you please try this and check if it fixes multiple modules issue?

**Comment by SalvatoreT** [comment]
I have a project with multiple modules that each contain their own `strings.xml` file, and 1.1.0 overwrote all of the strings by making only one `strings.xml` file.

<img width="1182" alt="Screen Shot 2020-06-03 at 2 59 58 PM" src="https://user-images.githubusercontent.com/1223008/83693458-f6b06480-a5aa-11ea-9c51-effd5563b3d8.png">

I'd like to second @AllanWang's suggestion.

> Easiest way to fix this is to store the absolute path as you send it

**Comment by AllanWang** [comment]
I believe my usage in the beginning was with the plugin, but since then, I've moved to github integrations so I can verify changes before merging. My approach is at https://github.com/AllanWang/KAU/blob/dev/crowdin.yml

---

If there are more details on which workflows this affects, I can try testing in the future

**Comment by SalvatoreT** [comment]
@andrii-bodnar, are you planning on having the Android Studio plugin support projects with multiple modules that each have their own `strings.xml` file?

**Comment by andrii-bodnar** [comment]
@SalvatoreT, yes, currently we are in the process of implementing this functionality.

**Comment by ImangazalievM** [comment]
@andrii-bodnar I have the same problem as Nick @SalvatoreT

**Comment by SalvatoreT** [comment]
@ImangazalievM, I received an email this morning from Olga, their customer success manager that the fix is underway.

> I just wanted to let you know that improvement for Android Studio plugin is already in testing stage and should be released in 2 weeks.

**Comment by andrii-bodnar** [comment]
Available in the [Version 1.2.0](https://github.com/crowdin/android-studio-plugin/releases/tag/1.2.0) :rocket:

**Comment by SalvatoreT** [comment]
@andrii-bodnar uploading the sources works in 1.2.0! I set `preserve-hierarchy=true`, and the source strings showed up in my dashboard. 👍 

However, I tried uploading translations, but that doesn't seem to work. Do I need to add something to the `crowdin.properties` file to get my pre-existing translations uploaded?

**Comment by andrii-bodnar** [comment]
Hi @SalvatoreT!

Happy to know that uploading sources work as expected! Could you please share your sources and translations files structure for all modules you localizing? It can help us to reproduce this problem.

**Comment by SalvatoreT** [comment]
Yep! Here are three modules that have translations.

```
./app/src/main/res/values-ar/strings.xml
./app/src/main/res/values-de/strings.xml
./app/src/main/res/values-es/strings.xml
./app/src/main/res/values-fr/strings.xml
./app/src/main/res/values-it/strings.xml
./app/src/main/res/values-ja/strings.xml
./app/src/main/res/values-pl/strings.xml
./app/src/main/res/values-pt/strings.xml
./app/src/main/res/values-ru/strings.xml
./app/src/main/res/values-zh/strings.xml
./app/src/main/res/values/strings.xml
./feature-a/src/main/res/values-ar/strings.xml
./feature-a/src/main/res/values-de/strings.xml
./feature-a/src/main/res/values-es/strings.xml
./feature-a/src/main/res/values-fr/strings.xml
./feature-a/src/main/res/values-it/strings.xml
./feature-a/src/main/res/values-ja/strings.xml
./feature-a/src/main/res/values-pl/strings.xml
./feature-a/src/main/res/values-pt/strings.xml
./feature-a/src/main/res/values-ru/strings.xml
./feature-a/src/main/res/values-zh/strings.xml
./feature-a/src/main/res/values/strings.xml
./network/src/main/res/values-ar/strings.xml
./network/src/main/res/values-de/strings.xml
./network/src/main/res/values-es/strings.xml
./network/src/main/res/values-fr/strings.xml
./network/src/main/res/values-it/strings.xml
./network/src/main/res/values-ja/strings.xml
./network/src/main/res/values-pl/strings.xml
./network/src/main/res/values-pt/strings.xml
./network/src/main/res/values-ru/strings.xml
./network/src/main/res/values-zh/strings.xml
./network/src/main/res/values/strings.xml
```

**Comment by andrii-bodnar** [comment]
@SalvatoreT, we can't reproduce this problem, could you please share your configuration file also? (without credentials)

**Comment by SalvatoreT** [comment]
```
project-id=405968
api-token=thisisasecret
disable-branches=true
auto-upload=false
preserve-hierarchy=true
```

**Comment by og-fox** [comment]
@SalvatoreT thanks a lot for sharing your configuration!

**Comment by andrii-bodnar** [comment]
Hi @SalvatoreT !

Could you please try this build with the possible fix?

[Crowdin-1.2.0.zip](https://github.com/crowdin/android-studio-plugin/files/4981286/Crowdin-1.2.0.zip)

**Comment by SalvatoreT** [comment]
It looks like this build only has "upload" options.
<img width="511" alt="Screen Shot 2020-07-27 at 12 17 19 PM" src="https://user-images.githubusercontent.com/1223008/88582666-f27d5200-d003-11ea-93ed-68970cefaee1.png">

When I tried both options, I got a pop-up asking if I wanted to upload, but then nothing happened afterwards. Previously, I had seen logs when I uploaded sources but not this time.

**Comment by Dmytro228** [comment]
Hi @SalvatoreT !

We're already investigating this

**Comment by frombetelgeuse** [comment]
Hi @SalvatoreT!

This problem usually when you add a lib/Crowdin-1.2.0.jar file from .zip archive instead of .zip archive itself. Could you please make sure that you've added it correctly?

[Updated Crowdin-1.2.0.zip](https://github.com/crowdin/android-studio-plugin/files/4987371/Crowdin-1.2.0.zip)

**Comment by SalvatoreT** [comment]
Ah, I _was_ using the `.jar`! I switched to using the `.zip`, so I saw the three options.
<img width="477" alt="Screen Shot 2020-07-28 at 10 45 03 AM" src="https://user-images.githubusercontent.com/1223008/88701915-7cd6bc00-d0bf-11ea-9226-ce3654c0c7af.png">

I could upload the sources.
```
10:36 AM	Crowdin: File 'app/src/main/res/values/strings.xml' is updated
```

Unfortunately, I couldn't upload the translations.

**Comment by ira-sem** [comment]
Hi Salvatore! Were there any errors or something when uploading translations? Any details would help

**Comment by SalvatoreT** [comment]
I see an uploading indicator, but nothing else happens.
![uploading-translations](https://user-images.githubusercontent.com/1223008/88703787-09827980-d0c2-11ea-8519-f387166eabf6.png)

I don't see anything in the Event Log, and there's nothing in the Android Studio logs here about the upload process.
```
~/Library/Logs/AndroidStudio4.0/idea.log
```

Is there some other place that I'd see error logs?

**Comment by og-fox** [comment]
Salvatore, thanks a lot for checking it! The errors usually appear like a pop-up window, so I assume there was nothing obvious. That definitely helps - we will be checking it further

**Comment by frombetelgeuse** [comment]
Hi @SalvatoreT!

Just now noticed that you have non-standard translation paths. When you don't specify any source/translation paths, plugin chooses to set standard pattern `**/values/strings.xml` for sources and `**/values-%android_code%/%original_file_name%` for translations. For your case, you have to explicitly set paths to all your sources. Like this:

```
files.source=/app/src/main/res/values/strings.xml
files.translation=/app/src/main/res/values-%two_letters_code%/strings.xml
files.2.source=/feature-a/src/main/res/values/strings.xml
files.2.translation=/feature-a/src/main/res/values-%two_letters_code%/strings.xml
files.3.source=/network/src/main/res/values/strings.xml
files.3.translation=/network/src/main/res/values-%two_letters_code%/strings.xml
```

Sorry for the inconvenience! 

Also, it seems to me that the plugin was not installed normally again, so if it does not work again, return to the version from the marketplace.

**Comment by SalvatoreT** [comment]
Hey @frombetelgeuse!

> Just now noticed that you have non-standard translation paths.

Non standard for Crowdin or non-standard for Android? The paths I'm using are standard for Android. You can read about them here. https://developer.android.com/guide/topics/resources/localization#creating-alternatives

You can also see a list of valid language codes here. https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources

> Also, it seems to me that the plugin was not installed normally again

What makes it seem this way to you? When I'm using the `.zip`, it's behaving very similarly to when I download the plugin from the marketplace. Please explain to me what I'm doing wrong.

**Comment by frombetelgeuse** [comment]
Hi @SalvatoreT,

I put it wrongly about non-standard paths. They are standard for both Crowdin and Android. But, when working with automatization of translation uploads, there is a need to specify more explicitly, which language codes are being used. Because of that, 'ar'([<ISO 639-1>](http://www.loc.gov/standards/iso639-2/php/code_list.php))(`%two_letters_code%` for Crowdin) and 'ar-rSA'([<ISO 639-1>](http://www.loc.gov/standards/iso639-2/php/code_list.php)-r[<ISO 3166-1-alpha-2>](https://www.iso.org/obp/ui/#iso:pub:PUB500001:en))(`%android_code%`) are completely different when uploading to Crowdin. What I meant by saying ‘non-standard’ is that by default, the plugin expects `%android_code%`(which is only non-standard in terms of the plugin itself), while for other variations there is a need to specify that in a configuration file. I hope I have correctly stated what I mean this time.

About the plugin, I don’t know for sure. The last changes to the build are made in such a way that, even if the translation files are absent(the plugin didn't find them), the message about that is displayed in the log. But that didn’t happen, so I don’t even know what to think.

And if my assumptions from the last message are right, it should work on a version from the marketplace, too, and the question about whether or not the build is installed correctly can be dismissed.

**Comment by SalvatoreT** [comment]
> What I meant by saying ‘non-standard’ is that by default, the plugin expects `%android_code%` (which is only non-standard in terms of the plugin itself), while for other variations there is a need to specify that in a configuration file. I hope I have correctly stated what I mean this time.

Can you make the plugin responsive so that it can figure out if the Android project is language maps to the Crowdin `two_letters_code` or `android_code`? It would be nice if the multi-module language support worked out of the box for any standard Android setup and developers didn't have to be aware of Crowdin's internal representations of the language codes.

I got everything working after explicitly calling out each of my modules.

```
files.source=/app/src/main/res/values/strings.xml
files.translation=/app/src/main/res/values-%two_letters_code%/strings.xml
files.1.source=/feature-a/src/main/res/values/strings.xml
files.1.translation=/feature-a/src/main/res/values-%two_letters_code%/strings.xml
files.2.source=/feature-b/src/main/res/values/strings.xml
files.2.translation=/feature-b/src/main/res/values-%two_letters_code%/strings.xml
files.3.source=/feature-c/src/main/res/values/strings.xml
files.3.translation=/feature-c/src/main/res/values-%two_letters_code%/strings.xml
...
files.10.source=/feature-j/src/main/res/values/strings.xml
files.10.translation=/feature-j/src/main/res/values-%two_letters_code%/strings.xml
```

**Comment by frombetelgeuse** [comment]
We have some ideas to make the interaction with the plugin more transparent. The plugin is currently in active development, so we are gradually moving towards this.

We are sorry for the inconvenience.
