### ISSUE TITLE
[help] avoid/ignore a directory

### ISSUE THREAD

**Issue by eneiluj** [crowdin/android-studio-plugin#36]
Hey, thanks a lot for this very useful plugin!

Since 1.0.0 (or 1.1.0 maybe), when I "Download Translations" from "Tools -> Crowdin", some translation files get deleted in a subdirectory of my repository. This is actually a git submodule containing translation files. The submodule source file was not uploaded to the Crowdin project. Those translation files have nothing to do with my project :grin:.

Here is my crowdin.properties:
```
project-id=
api-token=
disable-branches=true
auto-upload=false
```

I guess I could use `files.source` and `files.translation` but I just want to keep default behaviour for my actual translation files.

I just want Crowdin plugin to ignore the subdirectory. Is there a way to do that?

**Comment by andrii-bodnar** [comment]
Hi @eneiluj !

Could you please provide more information about the localization files hierarchy in your project and which ones were deleted? It will help us to reproduce this problem

Also, please try to [download](https://plugins.jetbrains.com/plugin/9463-crowdin/update/86508) and install v1.0.0 and then check this version. It also can help us to reproduce the problem.

**Comment by eneiluj** [comment]
Thanks for your answer.

I forgot to mention I have the plugin v1.1.0 installed. Would you still like me to downgrade it to v1.0.0?

So my source and translation files are there:
```
app/src/main/res/values/strings.xml
app/src/main/res/values-xx-rXX/strings.xml
```
They are updated correctly when requesting translations from Crowdin.

The files that get deleted are there:
```
cert4android/src/main/res/values-pt-rBR/strings.xml
cert4android/src/main/res/values-sl-rSI/strings.xml                                         
cert4android/src/main/res/values-tr-rTR/strings.xml                                         
cert4android/src/main/res/values-zh-rCN/strings.xml                                                                                                                                                   
cert4android/src/main/res/values-zh-rTW/strings.xml
```
I don't know why those files are deleted and the others are not.

If you want to reproduce the problem, my Crowdin project ID is `moneybuster`. You can clone the repo:
```
git clone --recurse-submodules https://gitlab.com/eneiluj/moneybuster
```
then place a `crowdin.properties` with token and ID (I guess you have access to that) and `disable-branches=true` and `auto-upload=false`, then import the project in Android studio and request new translations with Crowdin plugin.

**Comment by andrii-bodnar** [comment]
@eneiluj, thanks for the details!

> Would you still like me to downgrade it to v1.0.0?

Just to check if this problem was before or appeared in the latest version. For regular use, I recommend the latest version :)

**Comment by eneiluj** [comment]
No problem with v1.0.0 so it appeared with v1.1.0

**Comment by andrii-bodnar** [comment]
Thanks, we are trying to fix it ASAP. Fix will be available in the next version.

Sorry for the inconvenience!

**Comment by eneiluj** [comment]
It was not such a big problem. Thanks a lot for considering it! :rocket:

**Comment by andrii-bodnar** [comment]
Hi, @eneiluj!

We are discovered more about your problem and figured out that it is related to the issue https://github.com/crowdin/android-studio-plugin/issues/3.

Version 1.0.0 considered only the first `strings.xml` file and this file was selected by this algorithm. But in v1.1.0 we have changed sources detection algorithm and from now we are considering all the `strings.xml` files.

Since this plugin hasn't multiple modules support for now (will be improved in the next versions), you need to use `files.source` and `files.translation` patterns to set up only needed source files.

Also, we are considering adding some config option to ignore directories.

Could you please try to use new `files.source` and `files.translation` patterns in v1.1.0?
