### ISSUE TITLE
Allow for the Personal Access Token outside crowdin.properties

### ISSUE THREAD

**Issue by SalvatoreT** [crowdin/android-studio-plugin#37]
**Is your feature request related to a problem? Please describe.**
The Crowdin documentation says to treat the personal access token like a password, yet the Android Studio plugin (and all the integrations) tell you to put it in a `crowdin.properties` file which in all likelihood will get checked into git.

**Describe the solution you'd like**
There's a few alternatives.

1. Allow for folks to store their personal access token in the plugin in Android Studio.
2. Create a profile system in the home directory with some way of storing different profiles (e.g. a `~/.crowdin` folder or file with ways of storing each project personal access token).
3. Add a path field in the `crowdin.properties` file for a place to store the personal access token that points outside the project.

**Comment by sergo-crowdin** [comment]
Hello Salvatore,

Thank you for the improvement idea. I'll pass that to our developers so that they could think how to implement that :)

**Comment by SalvatoreT** [comment]
Thank you, @sergo-crowdin!

**Comment by andrii-bodnar** [comment]
Available in the [Version 1.2.0](https://github.com/crowdin/android-studio-plugin/releases/tag/1.2.0) :rocket:
