### ISSUE TITLE
[config question] Files for different app flavours

### ISSUE THREAD

**Issue by AgneseBussone** [crowdin/android-studio-plugin#38]
Hello, 
I have an app with two different flavour and each one has a localised name. I'm trying to setup the plugin to sync with the files I currently have in my crowdin project, but I'm having some issue understanding what's the right setup for my case.

The files are in these folders:
projectName/app/src/**main**/res/values/strings.xml
projectName/app/src/**main**/res/values/app_name.xml
projectName/app/src/**flavourA**/res/app_name.xml

I'm using the plugin version `1.1.0` and this is what I have for the first two files (main folder)
```
files.source=/values/strings.xml
files.translation=/values-%android_code%/%original_file_name%
files.1.source=/values/app_name.xml
files.1.translation=/values-%android_code%/%original_file_name%
```
What's the correct setup for the app_name.xml file in the flavourA folder?

I don't know if the settings in the website count, but I wasn't able to get the right path from that either: if I build&download, I get this structure
projectName/values-xx/strings.xml
projectName/values-xx/app_name.xml
projectName/xx/flavourA/app_name.xml 
The last one is always wrong, no matter the tree or settings (expected projectName/flavourA/values-xx/app_name.xml)

If I upload from the plugin, should I expect the uploaded files to match the ones I already have in crowdin? I mean, if uploading from the plugin changes the tree in crowdin, will I lose all the translations?

Thank you.

**Comment by andrii-bodnar** [comment]
Hi, @AgneseBussone!

The current behavior of Crowdin Android Studio Plugin is uploading files to the Crowdin project root (or branch if `disable-branches` is set to `false`). It works for simple cases when all the source files have different names. 

> If I upload from the plugin, should I expect the uploaded files to match the ones I already have in crowdin? I mean, if uploading from the plugin changes the tree in crowdin, will I lose all the translations?

Plugin uploads files to the project root, so if your existing Crowdin files are located in the root, everything should be ok.

Just let me clarify: do you need to upload file `projectName/app/src/flavourA/res/app_name.xml` to Crowdin?

**Comment by AgneseBussone** [comment]
Thanks for the fast response!

> Just let me clarify: do you need to upload file projectName/app/src/flavourA/res/app_name.xml to Crowdin?

No, this file is already in crowdin. The tree I have in crowdin is
flavourA/app_name.xml
main/strings.xml
main/app_name.xml

It would be nice to be able to sync app_name.xml files, but if the plugin doesn't support this case I think it would be fine. It's not that the app name changes all the time to require a constant sync 😄 

In case I want to sync only strings.xml with the plugin, leaving the other files already present in crowdin untouched, how should I organise the files in crowdin?

**Comment by andrii-bodnar** [comment]
Just move your `strings.xml` and `app_name.xml` files to the Crowdin project root, existing translations will be saved. Then you can simplify your `crowdin.properties` file in the next way:

```
project-id=your-project-identifier
api-token=your-api-token
sources=strings.xml, app_name.xml
disable-branches=true
auto-upload=false
```

The plugin will not synchronize `flavourA/app_name.xml` file, only `values/strings.xml` and `values/app_name.xml` will be synced.

Currently, we are preparing an improvement where will be allowed to upload sources with the same names, preserving files structure.

**Comment by AgneseBussone** [comment]
Ok, thanks for your help!
