### ISSUE TITLE
Add dialog "Are you sure?" after click on the "Upload Translations" button.

### ISSUE THREAD

**Issue by n0vah** [crowdin/android-studio-plugin#39]
Now it's easy to miss click on the "Upload Translations" button and all translations will be rewritten on Crowdin.

**Comment by og-fox** [comment]
@n0vah thanks a lot for pointing that out! We'll definitely make an improvement for translation upload

**Comment by andrii-bodnar** [comment]
Available in the [Version 1.2.0](https://github.com/crowdin/android-studio-plugin/releases/tag/1.2.0)

**Comment by n0vah** [comment]
Thanks
