### ISSUE TITLE
Feature Request: Add option to only download approved translations

### ISSUE THREAD

**Issue by andrew-polk** [crowdin/android-studio-plugin#4]
Currently, download gets all strings whether they have been approved or not.
The user should be able to specify if he wants to only download approved translations.

**Comment by v3ctorman** [comment]
@andrew-polk 
Have you tried to hit the option **Export only approved translations** in project settings (first tab)?
http://bit.ly/2tb9xft

**Comment by andrii-bodnar** [comment]
**Export only approved translations** in project settings
