### ISSUE TITLE
Always failed to upload source strings.

### ISSUE THREAD

**Issue by BillHoo** [crowdin/android-studio-plugin#45]
**Describe the bug**
It is very strange, the Crowdin Plugin 1.2.0 is always failed to upload source strings even from a brand new demo project.

**To Reproduce**
1. Install the plugin from Android Studio > settings > plugins > repository. Restart the IDE to make it available.
2. Add the `crowdin.properties` file to the root of project.
3. Just add two lines into it: `project-id (numeric)` and `api-token`, i could confirm these parameters are correct because i can see API call in my Crowdin UI (project settings > API & Webhooks > Calls History).
4. Once done, change the source string (auto upload), or click the "Tools > Crowdin > Upload sources" button manually.
5. The plugin shows me "Could not upload source strings" every time.

**Environment:**
 Android Studio version 4.0.1

**Expected behavior**
Work like it said in the docs.

**Screenshots**
![351F9D8E-71CB-4A0C-953C-D4DF5F1C4E87](https://user-images.githubusercontent.com/4627690/93156501-da3fce80-f73a-11ea-919f-1b911a5782ad.png)

**Comment by BillHoo** [comment]
Its not my source string quote limit i guess, cos' i've deleted a lot strings before the test, it still not working, the Android Demo peoject have only 10 strings to upload.

**Comment by Olena1234** [comment]
Bill, thank you for the details! Checking them with our devs

**Comment by nataliacrowdin** [comment]
Hi Bill!
As I see you still have the number of hosted words used almost completely: "2 more hosted words can be uploaded"
Because of this reason you cannot fill the source files

**Comment by BillHoo** [comment]
@nataliacrowdin Hi Natalia, i confirm that i have enough strings. I've deleted a lot strings before, and at least remains 3000 hosted words, and then use the Android brand new project which have only 10 strings (maybe 40 hosted words), still failed.

**Comment by BillHoo** [comment]
BTW, i'm trying to buy more hosted words these days, will test again after that.

And i think your plugin could be better if you detect there's a limit, you said it out to us, like "Your hosted words are reached the limit, upload source failed", instead of a general "Failed to upload source strings" error message.

**Comment by andrii-bodnar** [comment]
Hi @BillHoo !

Sorry for the inconvenience, we are still trying to reproduce and fix this issue.

Could you please tell us which OS are you using?

**Comment by BillHoo** [comment]
Windows 10

**Comment by andrii-bodnar** [comment]
Do you have the possibility to try to run the plugin on another computer with a different OS? Just in case

**Comment by BillHoo** [comment]
Sure, i will try it when i'm available.

**Comment by BillHoo** [comment]
Update: The plugin is work on Mac OS system. Windows 10 still fails.

**Comment by andrii-bodnar** [comment]
HI @BillHoo !
Thanks for the update. I'm sure it will help us a lot in solving this issue.

**Comment by BillHoo** [comment]
Hi there, any update on this topic? thank you.

**Comment by andrii-bodnar** [comment]
Hi @BillHoo, 

The issue is fixed and currently is being tested by our QA team.

For now, you can try a plugin version with the fix: [Crowdin-1.2.0.zip](https://github.com/crowdin/android-studio-plugin/files/5296876/Crowdin-1.2.0.zip)

Could you please confirm that everything is ok?

**Comment by BillHoo** [comment]
Hi @andrii-bodnar , confirmed it is worked now, waiting for your officially release.

Thanks for your team's effort on this!
