### ISSUE TITLE
Feature Request: Add option to download only certain files

### ISSUE THREAD

**Issue by andrew-polk** [crowdin/android-studio-plugin#5]
We have a Crowdin project which is used for many files, including our Android app.
When I download using the plugin in Android Studio, I get all those other files when all I want are the strings.xml files for the Android app.

**Comment by v3ctorman** [comment]
@andrew-polk thanks for the request. As a possible workaround, you can create a separate project just for Android app ([translations can be shared](https://support.crowdin.com/translation-memory/#assigning-tm)) so you'll be able to download only Android-related files. 
If your project is under open source license, we can extend the project limit for this purpose.
