### ISSUE TITLE
Release 1.3.1

### ISSUE THREAD

**Issue by n-belokopytov** [crowdin/android-studio-plugin#53]
**Is your feature request related to a problem? Please describe.**
Seems like there is an improved error wrapper in code already. Our plugin has stopped working in December and I would love to fix the integration, but without any error logging it's impossible.

**Describe the solution you'd like**
Please release the new version that has better error logging.

**Comment by n-belokopytov** [comment]
@andrii-bodnar ping

**Comment by andrii-bodnar** [comment]
Hi @n-belokopytov!
Sure, I will release a new version today.

**Comment by andrii-bodnar** [comment]
@n-belokopytov, just released the new version, I will close this issue.

Please try this version and if you will still see problems with the plugin, please create a new issue or [Contact](https://crowdin.com/contacts) Customer Success Service.
