### ISSUE TITLE
Download a specific Translations not all translations

### ISSUE THREAD

**Issue by nhammami** [crowdin/android-studio-plugin#58]
In my Android project i have many Flavors, each flavor have some languages, so i need for example for flavor "X" to download only the translations of two languages, and for Flavor "Y" i want to download the translations of four languages, But what I see in crowdin Android Studio plugin, I can't choose a specific languages to download.

I try  Tools -> Crowdin -> download Translations ,but it download all supported languages in my crowdin project. 

Can I configure that ? or this feature is not supported yet ?

I try also to change the languages that i need for a specific source file Strings.XML, 

![Capture d’écran du 2021-05-19 10-44-19](https://user-images.githubusercontent.com/84445226/118792286-6dfc0880-b88f-11eb-9fbb-bfbd7103b093.png)

and try again Tools -> Crowdin -> download Translations but i got this warning message 
![Capture d’écran du 2021-05-19 10-50-14](https://user-images.githubusercontent.com/84445226/118793171-435e7f80-b890-11eb-872a-77a31d9dbd08.jpg)

**Comment by andrii-bodnar** [comment]
There is a "Download Translation File from Crowdin" action in the context menu for a translation file that allows downloading translations only for this language.

![image](https://user-images.githubusercontent.com/29282228/197191504-3436fd45-1a7f-4337-be0a-11e0af00ad55.png)
