### ISSUE TITLE
Add the ability to use different crowdin.properties for different flavors

### ISSUE THREAD

**Issue by EvgeniyKu** [crowdin/android-studio-plugin#59]
I have several flavors in a project and want to use a separate project in crowdin for each flavor. But now i can't specify several crowdin.properties in one project. The same issue may be in case, when using several application modules.

Can the plugin grab the crowdin.properties file depending on the flavor selected?
If no, can we define several properties in root folder (like crowdin-flavor1.properties, crowdin-flavor2.properties) and show submenu for each properties file (like Tools->Crowdin->flavor1->Upload Sources; Tools->Crowdin->flavor2-> Upload Sources) ?

**Comment by nhammami** [comment]
Hi Crowdin Team,

I have the same issue @EvgeniyKu , i  want to use a separate project in Crowdin for each of my flavors, is this feature can be added in the next version of android studio plugin ?

Best Regards,
Nouha.

**Comment by andrii-bodnar** [comment]
Hi @nhammami!

We will consider the possibility of increasing the priority of this issue. Could you please share some sample Android project that includes different flavors?

This could help us to correctly design this feature. Thanks.

**Comment by nhammami** [comment]
Hi @andrii-bodnar 

So you can check this [Sample Android Flavor project](https://github.com/Goldenmace/android_flavoring)

you can see in this project there is three flavors :

- free
- paid
- promo

and the configuration in gradle

```
productFlavors {
        free {}
        paid {}
        promo {}
    }
```

Thank you for your attention.

Best Regards,
Nouha.

**Comment by andrii-bodnar** [comment]
Hi @nhammami

Thanks a lot for the details provided!

**Comment by nhammami** [comment]
Thank for you @andrii-bodnar 

Let me now please if this feature will be applied.

Thanks,

Best Regards,
Nouha.

**Comment by SteinerOk** [comment]
Any updates with this issue?

**Comment by andrii-bodnar** [comment]
Hi @SteinerOk!

Currently, there is a possibility to use only a single `crowdin.properties` file but configure patterns for each flavor.

https://github.com/crowdin/android-studio-plugin#filessourcetranslation-parameters

for example:

```properties
files.source=**/values/strings.xml
files.translation=/values-%two_letters_code%/%original_file_name%

files.1.source=app/src/main/res/values/file.xml
files.1.translation=app/src/main/res/values-%android_code%/%original_file_name%
files.2.source=ext/src/main/res/values/file.xml
files.2.translation=ext/src/main/res/values-%android_code%/%original_file_name%

```

**Comment by SteinerOk** [comment]
@andrii-bodnar I'm in a more difficult situation.

I have several productFlavors, so at the same time I need to decompose the translations into different folders, depending on the language, for example:

```
Primary language
app/src/main/res/values/strings.xml
Turkish
app/src/omni/res/values-tr/strings.xml
English
app/src/polidesk/res/values-en/strings.xml
```

**Comment by andrii-bodnar** [comment]
@SteinerOk, hmm, the source file is located in one module and translation files should be placed inside the other modules?

**Comment by SteinerOk** [comment]
@andrii-bodnar no, all files in the same module (**app**), but translation placed in different **productFlavors**.
We have 2 productFlavors:  **omni** and **polidesk**
For **omni** we need translation to Turkish, and for **polidesk** we need translation for English

**Comment by Yakoot** [comment]
Hello!
Any news about settings for flavors?
We have structure like this, main app and two apps based on the main, but with another translations, another languages etc
app
--main
----values
------strings.xml
----values-id
------strings.xml
----values-zh
------strings.xml
----values-hi
------strings.xml
--flavor1
----values
------strings.xml
----values-id
------strings.xml
--flavor2
----values
------strings.xml
----values-de
------strings.xml
----values-es
------strings.xml

**Comment by andrii-bodnar** [comment]
@Yakoot there are no updates regarding flavors. Did you try to set up patterns for each flavor like in [this](https://github.com/crowdin/android-studio-plugin/issues/59#issuecomment-1096756737) example?
