### ISSUE TITLE
All options in settings file crowdin.properties

### ISSUE THREAD

**Issue by nhammami** [crowdin/android-studio-plugin#60]
Here i want to ask about all the options that i can configure it in crowdin.properites 

project-id
api-token
preserve-hierarchy
auto-upload

files.source
files.translation

No more options ? 

cannot add a target language for translation for each file.source ?

best Regards,
Nouha.

**Comment by BozhenaDobrovolska** [comment]
Hi Nouha!

Here is a documentation to view:
https://support.crowdin.com/android-studio/

**Comment by nhammami** [comment]
Hi @BozhenaDobrovolska , @andrii-bodnar ! 

thanks for your reply,

I have other question about languages, i do some search and i read all documents about crowdin, but i can't find how to configure or it's possible to use a different placeholders for the same files.translation for example, in my project i have the French and Spanish languages (values-fr, values-es) so i use in my `crowdin.properties` `files.translation=**/values-%two_letters_code%/%original_file_name%`

but also i have for Chinese language, three different files,  values-zh-rCN, values-zh-rHK and values-zh-rTW, so here i should use other placeholders `%android_code%` , i can't use a different placeholders for the same file.source ?? 

I want to use 
` files.translation=**/values-%two_letters_code%/%original_file_name%` for french and Spanish and
` files.translation=**/values-%android_code%/%original_file_name%` for Chinese language

Best Regards,
Nouha.

**Comment by Olena1234** [comment]
Hi @nhammami ! I believe that setting up language mapping for two of the four languages would help here, kindly check more details below:
https://support.crowdin.com/advanced-project-setup/#adding-custom-language-codes

Then you may use only one placeholder for all languages in the exported path

**Comment by nhammami** [comment]
hi @Olena1234 ,

Thanks for your quick reply.

**Comment by nhammami** [comment]
hi @andrii-bodnar 

I see that a new option was added excluded-target-languages, can i used it to exclude some languages for any file.source ?

Best Regards,
Nouha.

**Comment by andrii-bodnar** [comment]
Hi @nhammami

Yes, you can use it for any files group in your configuration file: 

```properties
# Applies to default behavior, `sources` parameter 
# and all filegroups that do not have such a configuration
excluded-target-languages=uk, fr

# or

files.source=...
files.excluded-target-languages=it, fr # For a specific filegroup, high priority
files.translation=...

files.1.source=...
files.1.excluded-target-languages=uk
files.1.translation=...

#etc.
```

**Comment by nightwolf13** [comment]
Hi,
I have next configuration for chinese language files:
![image](https://user-images.githubusercontent.com/30594754/169256613-c8d9cb4e-d566-4099-9ebe-273f91ceaf58.png)
So where zh, zh-rCN - simplified chinese
And zh-rTW, zh-rMO, zh-rHK - traditional chinese
I want to have just 2 languages in crowdin (simplified chinese and traditional chinese)
And update all files properly..
Is it possible to configure it using properties and crowdin mapping?
I'm not fully understand how it works :( in both ways:
1) when I upload the sources/translations
2) when I download translations

**Comment by nightwolf13** [comment]
> Hi @nightwolf13, languages in the Crowdin project should correspond to languages in the Android Studio project

So I have to have 5 languages in the crowdin, even the real there is only 2 real translations?
How should I configure crowdin.properties in this case, because i have 1 chinese language available by two-letters code, and 4 languages with 'android-code'?

**Comment by andrii-bodnar** [comment]
@nightwolf13 what is your source language?

**Comment by nightwolf13** [comment]
@andrii-bodnar , english

**Comment by andrii-bodnar** [comment]
@nightwolf13 thank you

What the difference between `zh` and `zh-rCN` languages in your project?

**Comment by nightwolf13** [comment]
@andrii-bodnar ,
Just app name (for chinese region it should be slightly different). Yes, the problem with simplified can be solved using just zh file.. But what about traditional chinese? As I know it's used in these 3 regions (rTW, rHK, rMO)..

**Comment by andrii-bodnar** [comment]
@nightwolf13 you need to create a custom language for the `ch` code (and set `zh` as an `%android_code%`)

Crowdin supports natively only the following codes:
![Знімок екрана 2022-05-19 о 14 33 14](https://user-images.githubusercontent.com/29282228/169284175-b47a0513-0761-49bf-b11d-e62ea8cde5e1.png)

Then add to your Crowdin project other languages and configure the `Automatically fill in regional dialects` option in the project settings. It is useful when the project is translated into the language dialects (e.g., Spanish, Argentina). Translations from Spanish will be automatically copied to untranslated strings in Spanish, Argentina during the download.

**Comment by nightwolf13** [comment]
@andrii-bodnar , Thanks!
Looks like Automatic filling can solve this problem..
But am I right that in this case I will use 5*n hosted words instead of 2*n?

**Comment by andrii-bodnar** [comment]
@nightwolf13 yes, currently there is no possibility to fill some languages with another language on the Crowdin Android Studio plugin side.

Though, on the other hand, the translation for some strings may be different for these dialects, so it may be incorrect to fill all the dialects (zh-TW, zh-HK, zh-MO) with just Chinese Traditional.
