### ISSUE TITLE
Allow putting api-token in the external file outside VCS directory

### ISSUE THREAD

**Issue by alecpetrosky** [crowdin/android-studio-plugin#62]
**Is your feature request related to a problem? Please describe.**
As a security measure, especially for opensource projects, it would be great to have an option of placing Crowdin api-key outside of version control.

**Describe the solution you'd like**
- Crowdin CLI client already reads .crowdin.yml with the highest priority.
- Add option to set file name with api-key (~ as gradle does for signing key passwords).

**Describe alternatives you've considered**
Currently, if someone wants to use this plugin, the only solution is adding crowdin.properties to .gitignore. Or using CLI client instead of AS Plugin.

**Comment by alecpetrosky** [comment]
Oh, I see that there's an option of using env variables api-token-env. It solves the problem. Not as good as external file but much better than putting Crowdin api-key under version control.

**Comment by Rommka4** [comment]
Hello Alec,
Glad to hear you found a solution and that the material collected here regarding android-studio-plugin is useful for you😊

**Comment by andrii-bodnar** [comment]
Hi @alecpetrosky!

you could load the credentials from environment variables:

```
project-id-env=CROWDIN_PROJECT_ID
api-token-env=CROWDIN_TOKEN
base-url-env=CROWDIN_BASE_URL
```

So, using this approach, the `crowdin.yml` file could be committed to the repository without compromising the credentials.
