### ISSUE TITLE
Add ability to user one more of crowdin.properties in main project

### ISSUE THREAD

**Issue by nhammami** [crowdin/android-studio-plugin#64]
I have several flavors in a project and want to use a separate project in crowdin for each flavor. But now i can't specify several crowdin.properties in one project.

If we add the ability to use one more of crowdin.properties files, so we can config each one for a separate project on Crowdin

Best Regards,
Nouha.

**Comment by andrii-bodnar** [comment]
Hi @nhammami! 

It seems like this issue duplicates the existing one - https://github.com/crowdin/android-studio-plugin/issues/59, is it right?

Sorry for the long response in the issue above, missed it somehow :grimacing:

**Comment by nhammami** [comment]
hi @andrii-bodnar ,

yes it's the same issue and we didn't have a response for that

**Comment by andrii-bodnar** [comment]
@nhammami I answered in #59, sorry for a long response

can we close the current issue?

**Comment by nhammami** [comment]
@andrii-bodnar  thank you.

yes please close it.
