### ISSUE TITLE
crowding.properties can't find environment variables from ~/.zprofile

### ISSUE THREAD

**Issue by n0vah** [crowdin/android-studio-plugin#67]
**Describe the bug**
I have crowdin.properties
```groovy
project-id=my_project_id
api-token-env=CROWDIN_API_KEY
disable-branches=true
auto-upload=false
files.source=/app/src/main/res/values/strings.xml
files.translation=/app/src/main/res/values-%two_letters_code%/%original_file_name%
```
And I added environment variable to the ~/.zprofile
`export CROWDIN_API_KEY=my_personal_access_token`

In terminal using `printenv` or` echo $CROWDIN_API_KEY` I see value of CROWDIN_API_KEY even after restart Mac OS, but when I start Android Studio or trying to use Crowdin plugin I see an error 
**Crowdin 
Errors in the configuration file: 
Environment variables do not contain 'CROWDIN_API_KEY' key**

But when I set environment variable using `launchctl setenv CROWDIN_API_KEY my_personal_access_token` Crowdin plugin see value of the CROWDIN_API_KEY variable and everything works fine until I restart Mac OS (after restart I don't see this variable neither in terminal or Android Studio).

Can you help me and say why plugin doesn't see variables from the `~/.zprofile` but see from  `launchctl setenv`, or I should add environment variable in another way that it will be visible for plugin (like `launchctl setenv` ) and won't be erased after Mac restart  (like `~/.zprofile`)?

**Environment:**
Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 26, 2021
macOS 11.5.2
Crowdin Android Studio plugin 1.4.1

**Comment by andrii-bodnar** [comment]
Hi @n0vah!

Sorry, but we can't reproduce this issue

Please make sure you restart your IDE or computer after environment variable export

Also, you could try to use the following way to initialize the environment variable in the `~/.zhsrc` file:

```
launchctl setenv CROWDIN_API_KEY my_personal_access_token
```

**Comment by n0vah** [comment]
Hi.
Yes I restarted my IDE and computer and this didn't helped for ~/.zprofile.

Thanks, adding `launchctl setenv CROWDIN_API_KEY my_personal_access_token` to the `~/.zhsrc` helped.

**Comment by kikasik** [comment]
same problem
