### ISSUE TITLE
Unfound sources when downloading translations

### ISSUE THREAD

**Issue by Andralisimus** [crowdin/android-studio-plugin#68]
Crowdin can't find sources for all translations when Tools -> Crowdin -> Download Translations

I have read documentation for like 10 times. Could not understand how files.source and files.translation should look. A tried multiple variants, but according to documentation process should work without this properties. So maybe this is bug.
I'll show everything in screenshots maybe you guys will have answers. It would help me a lot)

1. Android Studio version 4.2.1
2. OS version: macOS Big Sur 11.4 

Download Translations should fill strings files with translations, but nothing happens. 

Log with debug=true:

<img width="693" alt="Log" src="https://user-images.githubusercontent.com/61683841/131810357-21405b78-b7e1-4d69-9126-6d04d3bbd92d.png">

Project structure inside res folder:

<img width="168" alt="res" src="https://user-images.githubusercontent.com/61683841/131810485-5f84cbc4-86cc-4077-9fa4-dd829622ee16.png">

Files structure in Crowdin:

![Files](https://user-images.githubusercontent.com/61683841/131810658-225eb0f4-2a5b-45f5-b1d0-29d68aaf599f.png)

crowdin.properties:

<img width="231" alt="properties" src="https://user-images.githubusercontent.com/61683841/131810758-c0146381-0c0c-445a-a960-9c10f3781811.png">

**Comment by andrii-bodnar** [comment]
Hi, @Andralisimus!
Could you please point how the strings.xml file was uploaded to the Crowdin project?

**Comment by Andralisimus** [comment]
@andrii-bodnar 
I wasn't there to know for sure but with 90% probability I can say that it was added with Add File button.

Can you please specify what should be done before downloading translations with plugin?
Because if I download strings.xml from files it's just default values, but if I go Home-> Download Latest, there will be latest translations which I need in project

<img width="799" alt="Screenshot 2021-09-02 at 13 51 37" src="https://user-images.githubusercontent.com/61683841/131831436-bd8ad77b-302f-4106-8fb3-1e1bee59672b.png">

**Comment by andrii-bodnar** [comment]
@Andralisimus try to upload sources (strings.xml) using Android Studio Plugin. Just click *Tools* > *Crowdin* > *Upload Sources*. It will update your strings.xml file in the Crowdin project and set the corresponding file export pattern. After that translations downloads should work correctly.

**Comment by Andralisimus** [comment]
@andrii-bodnar 
Things changed, that's a good news. Now debug shows:
`Translation file '/values-pl-rPL/strings.xml' - Found`
as well as all other languages

And in res folder I now have `values-pl-rPL` package.

Could you please assist me I one more thing?
How can I get rid of -rPL part through `crowdin.properties` ?

**Comment by andrii-bodnar** [comment]
@Andralisimus, the *resulting file after translations export* field should be the same as *files.translation* value

**Comment by Andralisimus** [comment]
@andrii-bodnar 
I spent some time to make `/values-%two_letters_code%/%original_file_name%` work.
But I couldn't. But that's okay) I decided to leave default format. 

Tools > Crowdin > Upload Sources made it, so thank you)
