### ISSUE TITLE
It always download translation into a new folder all1321421....

### ISSUE THREAD

**Issue by van-tran** [crowdin/android-studio-plugin#69]
**Describe the bug**
I've tried many configuration for target translation file. Like this : 
`
files.source=**/values/strings.xml
files.translation=**/values-%two_letters_code%/strings.xml
`

**Expected behavior**
I expect the translation file should be put in the right folder of android project. (app/src/main/res/values-en/strings.xml). 

**Screenshots**
![image](https://user-images.githubusercontent.com/5194808/134538768-9d507104-e287-4dc6-baf4-da17c9084f7e.png)

Is it your expectation? or I missed anything? Could you help explain please?

**Comment by andrii-bodnar** [comment]
Hi @van-tran!
Please try to use absolute paths in your configuration.

**Comment by van-tran** [comment]
Oh. Thanks @andrii-bodnar .
So my team will need update the absolute paths if they clone the project at different places, right?

**Comment by andrii-bodnar** [comment]
@van-tran sorry, I mean absolute paths relative to your project:

```
files.source=app/src/main/res/values/strings.xml
files.translation=app/src/main/res/values-%two_letters_code%/strings.xml
```

**Comment by van-tran** [comment]
Great. Thank you, @andrii-bodnar .
Last times, I have tried with files.source=/app/src/main/res/values/strings.xml (starting with a / ) like the sample :
https://support.crowdin.com/android-studio/

The Document is pretty confusing me. 

Anyway, thank you.

**Comment by van-tran** [comment]
note: I just tried files.source=/app/src/main/res/values/strings.xml . It also works. 
I have no idea why it went wrong last days. 
Thanks

**Comment by Jeff11** [comment]
Got the same problem. Absolute paths for `files.source` and `files.translation` didn't fix it :(

I know it worked a few months ago, when I configured the `crowdin.properties` for our project.

This is the `crowdin.properties` file

```
project-id=xxxxx
api-token=xxxxxxxxx
disable-branches=true
auto-upload=false

files.source=appname/src/main/res/values/strings.xml
files.translation=appname/src/main/res/values-%two_letters_code%/%original_file_name%

```

**Comment by andrii-bodnar** [comment]
Hi @Jeff11!
We can't reproduce this issue. Could you please share the sample project where the issue is easily reproducible?

**Comment by WVerlaek** [comment]
Had the same issue, what fixed it for me was to upload sources.

What triggered the issue for me:
- Refactored my app from a single module into a multi-module architecture, moving all string resources from the default `app/` module to a new `libraries/ui-components/` module
- Updated `crowdin.properties` to include:
  ```
  files.source=libraries/ui-components/src/main/res/values/strings.xml
  files.translation=libraries/ui-components/src/main/res/values-%android_code%/%original_file_name%
  ```
- Tried to `Download Translations` from within Android Studio
- Files were downloaded as `all.zip` + `all764371223966800/*`

After doing `Upload Sources` once, the next `Download Translations` put all files in the right place in the new module
