### ISSUE TITLE
New import options for translations upload

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/android-studio-plugin#78]
**Is your feature request related to a problem? Please describe.**

Currently, the "Upload Translations" option is not configurable and doesn't allow applying additional import options to the uploaded translations.

The [Upload Translations](https://developer.crowdin.com/api/v2/#operation/api.projects.translations.postOnLanguage) API supports the following request parameters:

- `importEqSuggestions` - Defines whether to add translation if it's the same as the source string
- `autoApproveImported` - Mark uploaded translations as approved
- `translateHidden` - Allow translations upload to hidden source strings 

**Describe the solution you'd like**

1. Add a new configuration options to the `crowdin.properties` configuration file:

```properties
# Applies to the default behavior and all filegroups that do not have such a configuration
import-eq-suggestions=true/false
auto-approve-imported=true/false
translate-hidden=true/false

# Ability to configure for specific file groups
# higher priority
files.1.import-eq-suggestions=true/false
files.1.auto-approve-imported=true/false
files.1.translate-hidden=true/false

files.2.import-eq-suggestions=true/false
...
```

3. Pass new values from the config to the `UploadTranslationsAction` > `RequestBuilder.uploadTranslation`
4. Describe new configurations in the Readme.

**Comment by andrii-bodnar** [comment]
@jivjen sure, thank you!

**Comment by jivjen** [comment]
@andrii-bodnar 
Created the below PR. 
Could you please help review it?
https://github.com/crowdin/android-studio-plugin/pull/81
