### ISSUE TITLE
Fix typo in UIUtil:confirmDialog method name

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/android-studio-plugin#79]
The first character of `UIUtil:confirmDialog` method name has a different encoding, it should be replaced with the regular `c` character.

![screenshot](https://user-images.githubusercontent.com/29282228/194259811-e8d1b7fc-8fff-4829-b3e5-da94830d2819.png)

https://github.com/crowdin/android-studio-plugin/blob/c3d04ea62a02ae25fbbc10073adf43c4d1ade37e/src/main/java/com/crowdin/util/UIUtil.java#L12

**Comment by manish-singh-bisht** [comment]
Hi @andrii-bodnar I can help you with this typo in UIUtil.java file.
Please assign me this.
Thank  you.

**Comment by manish-singh-bisht** [comment]
By regular 'c' character you mean the **latin small letter 'c'**?

**Comment by andrii-bodnar** [comment]
Hi @manish-singh-bisht great, thank you!

> By regular 'c' character you mean the latin small letter 'c'?

Yes, the Latin small letter 'c'
