### ISSUE TITLE
Add missing Unit tests for the `CrowdinFileUtil.java` class

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/android-studio-plugin#82]
The `CrowdinFileUtil.java` class has low Unit test coverage. It would be great to add the missing Unit tests.

- [Actual coverage](https://app.codecov.io/gh/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/CrowdinFileUtil.java)
- [CrowdinFileUtilTest.java](https://github.com/crowdin/android-studio-plugin/blob/master/src/test/java/com/crowdin/util/CrowdinFileUtilTest.java)
- [CrowdinFileUtil.java](https://github.com/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/CrowdinFileUtil.java)

**Comment by Sakshi-75** [comment]
Hi @andrii-bodnar ,
I would like to work on this. Can you assign it to me?

**Comment by andrii-bodnar** [comment]
Hi @Sakshi-75, thank you! Please let me know if you need any assistance with that

**Comment by Sakshi-75** [comment]
Hi @andrii-bodnar ,
I've raised a PR for this: https://github.com/crowdin/android-studio-plugin/pull/87
I added coverage for almost the complete file. Only 2 lines of code are missed as it was an exception scenario in a private method.
