### ISSUE TITLE
Add missing Unit tests for the `PlaceholderUtil.java` class

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/android-studio-plugin#83]
The `PlaceholderUtil.java` class has low Unit test coverage. It would be great to add the missing Unit tests.

- [Actual coverage](https://app.codecov.io/gh/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/PlaceholderUtil.java)
- [PlaceholderUtilTest.java](https://github.com/crowdin/android-studio-plugin/blob/master/src/test/java/com/crowdin/util/PlaceholderUtilTest.java)
- [PlaceholderUtil.java](https://github.com/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/PlaceholderUtil.java)

**Comment by sivasuriyankumarasamy** [comment]
Hi @andrii-bodnar, I would like to work on this. please assign this to me.

**Comment by andrii-bodnar** [comment]
Hi @sivasuriyankumarasamy, thank you! Please let me know if you need any assistance with that

**Comment by sivasuriyankumarasamy** [comment]
Hi @andrii-bodnar,

In PlaceholderUtil.class, formatForRegex method is non static. As PlaceholderUtil class does not have public constructor I could not call formatForRegex method from test class.

I think we have below 2 option.
Option 1) We can make formatForRegex method as static and write the test cases.
Option 2) If not we cannot write the test cases as of now.

Please help me with this situation.

**Comment by andrii-bodnar** [comment]
@sivasuriyankumarasamy just checked the code and it seems like the `formatForRegex` method is not even used anywhere else. It looks like we can remove this method, isn't it?

**Comment by sivasuriyankumarasamy** [comment]
yes @andrii-bodnar. we can remove. can I remove and raise PR?

**Comment by andrii-bodnar** [comment]
@sivasuriyankumarasamy sure. Or it can be removed along with the tests added

**Comment by sivasuriyankumarasamy** [comment]
@andrii-bodnar I have raised a PR for this ticket. Please review.

https://github.com/crowdin/android-studio-plugin/pull/90
