### ISSUE TITLE
Add missing Unit tests for the `PropertyUtil.java` class

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/android-studio-plugin#84]
The `PropertyUtil.java` class has low Unit test coverage. It would be great to add the missing Unit tests.

- [Actual coverage](https://app.codecov.io/gh/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/PropertyUtil.java)
- [PropertyUtilTest.java](https://github.com/crowdin/android-studio-plugin/blob/master/src/test/java/com/crowdin/util/PropertyUtilTest.java)
- [PropertyUtil.java](https://github.com/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/PropertyUtil.java)

**Comment by Gowrishankar04** [comment]
Hi @andrii-bodnar,

I am interested in it, Can you please assign it to me?

Thanks

**Comment by andrii-bodnar** [comment]
Hi @Gowrishankar04, thank you! Please let me know if you need any assistance with that

**Comment by Gowrishankar04** [comment]
Hi @andrii-bodnar ,

Raised PR: https://github.com/crowdin/android-studio-plugin/issues/84
Please review and merge it.

Thanks

**Comment by andrii-bodnar** [comment]
Hi @Gowrishankar04, please check my comments on that PR
