### ISSUE TITLE
Add missing Unit tests for the `LanguageMapping.java` class

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/android-studio-plugin#85]
The `LanguageMapping.java` class has low Unit test coverage. It would be great to add the missing Unit tests.

- [Actual coverage](https://app.codecov.io/gh/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/LanguageMapping.java)
- [LanguageMapping.java](https://github.com/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/LanguageMapping.java)

**Comment by robertberes** [comment]
Hi @andrii-bodnar I would like to work on this. Could you please assign it to me?

**Comment by ImnIrdst** [comment]
Hey, I want to work on this. Can you please assign me to it?

**Comment by andrii-bodnar** [comment]
@ImnIrdst thank you! Please let me know if you need any assistance with that.
