### ISSUE TITLE
Add custom directory to source file

### ISSUE THREAD

**Issue by stprima** [crowdin/android-studio-plugin#9]
Is there a way to add custom file directory for the crowdin plugin?
The Crowdin plugin only seems to be checking for the source files under `{MainProject|/res/values/customstrings.xml`
The issue is, my source file is located inside `{MainProject}/assets/language/customstrings.xml`

This is my current crowdin.properties configuration, but it does nothing
`project-identifier=testproj`
`project-key=abc`
`sources={MainProject}/assets/language/customstrings.xml`
`disable-branches=true`
`auto-upload=false`

This seems to work, but only when the customstrings.xml file is under res/values
`project-identifier=testproj`
`project-key=abc`
`sources=customstrings.xml`
`disable-branches=true`
`auto-upload=false`

**Comment by Gosteeva** [comment]
Hello!

That is true that plugin checks the files from values directory. `sources` parameter is meant to contain the list of the files you would like to synchronize. If you will not specify it, only _strings.xml_ will be synchronized by default.

I will check with the developers if we can do anything to customize this behavior according to your needs and get back with the news!

**Comment by stprima** [comment]
That is great! Thanks for the quick response!

**Comment by Gosteeva** [comment]
Hello @stprima! I'm back here with the news! Idea of setting the custom directories in plugin config got approved by the upper management. It might take some time to get it on track, but you will be the first to know once the feature launch

Is it possible for you to store the files in `{MainProject|/res/values/customstrings.xml` as a temporary decision?

**Comment by stprima** [comment]
Hi @Gosteeva is there any update on this item?

**Comment by yuliiaR** [comment]
Hi @stprima The task is already on "to do" stage and should be implemented in the near future.

As soon as it is ready, we will immediately notify you about that :)
