### ISSUE TITLE
Increase code coverage for the `FileUtil` class

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/android-studio-plugin#91]
This class is an important part of the plugins, so it should be carefully covered by Unit tests.

- [Actual coverage](https://app.codecov.io/gh/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/FileUtil.java)
- [FileUtil.java class](https://github.com/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/FileUtil.java)
- [FileUtilTest.java class](https://github.com/crowdin/android-studio-plugin/blob/master/src/test/java/com/crowdin/util/FileUtilTest.java)

**Comment by Sakshi-75** [comment]
Hi @andrii-bodnar ,
Can I work on this?

**Comment by Sakshi-75** [comment]
Hi @andrii-bodnar ,
I've raised a PR for this: https://github.com/crowdin/android-studio-plugin/pull/94
Please review it.
