### ISSUE TITLE
Add Unit tests for the `GitUtil` and `ActionUtils` classes

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/android-studio-plugin#92]
- [GitUtil.java actual coverage](https://app.codecov.io/gh/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/GitUtil.java)
- [ActionUtils.java actual coverage](https://app.codecov.io/gh/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/ActionUtils.java)
- [GitUtil.java](https://github.com/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/GitUtil.java)
- [ActionUtils.java](https://github.com/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/ActionUtils.java)

**Comment by Sakshi-75** [comment]
Hi @andrii-bodnar ,
Can I work on this?

**Comment by andrii-bodnar** [comment]
Hi @Sakshi-75, sure, thank you!

**Comment by andrii-bodnar** [comment]
Hi @Sakshi-75, do you need any assistance here? Just wondering what the progress on this issue

**Comment by Sakshi-75** [comment]
Hi @andrii-bodnar , sorry about the delay. I've started working on this and will try to finish it in a couple of days.

**Comment by Sakshi-75** [comment]
Hi @andrii-bodnar , I'm facing issue in trying to create a Project object for the tests. Can you suggest me a way to do it?
I tried using ProjectManager to create one but that requires an ApplicationManager which requires Application and so on.
Is there any simpler way to create a Project object?

**Comment by andrii-bodnar** [comment]
Hi @Sakshi-75, it's an interesting case, didn't notice that before. I'm afraid that it could be impossible to mock this object

**Comment by Sakshi-75** [comment]
Hi @andrii-bodnar so how should we proceed in this case since the project object is mandatory in both these until classes?

**Comment by andrii-bodnar** [comment]
@Sakshi-75 I guess we have to skip these classes, I should have noticed that before creating this issue

**Comment by andrii-bodnar** [comment]
@Sakshi-75 you can write some Unit tests for some other part of the application if you wish

**Comment by andrii-bodnar** [comment]
@Sakshi-75 great, thanks a lot for your involvement!
