### ISSUE TITLE
 Improve tests coverage for the `CrowdinPropertiesLoader.java` class

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/android-studio-plugin#99]
The CrowdinPropertiesLoader is an essential part of the application and should be carefully covered by Unit tests.

- [Actual coverage](https://app.codecov.io/gh/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/client/CrowdinPropertiesLoader.java)
- [CrowdinPropertiesLoaderTest.java](https://github.com/crowdin/android-studio-plugin/blob/master/src/test/java/com/crowdin/client/CrowdinPropertiesLoaderTest.java)
- [CrowdinPropertiesLoader.java](https://github.com/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/client/CrowdinPropertiesLoader.java)

**Comment by Gowrishankar04** [comment]
Hi @andrii-bodnar ,

Can you please assign this to me ?

Thanks

**Comment by andrii-bodnar** [comment]
Hi @Gowrishankar04, sure, thank you!
